// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real_Estate.Data;

namespace Real_Estate.Migrations
{
    [DbContext(typeof(RealEstateContext))]
    [Migration("20200818170608_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Real_Estate.Model.Apartamento", b =>
                {
                    b.Property<int>("cod_apartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Imovelcod_imovel")
                        .HasColumnType("int");

                    b.Property<int?>("Proprietariocod_proprietario")
                        .HasColumnType("int");

                    b.Property<string>("nome_bloco")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<byte>("numero_bloco")
                        .HasColumnType("TINYINT");

                    b.HasKey("cod_apartamento");

                    b.HasIndex("Imovelcod_imovel");

                    b.HasIndex("Proprietariocod_proprietario");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("Real_Estate.Model.Casa", b =>
                {
                    b.Property<int>("cod_casa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Imovelcod_imovel")
                        .HasColumnType("int");

                    b.Property<int?>("Proprietariocod_proprietario")
                        .HasColumnType("int");

                    b.Property<bool>("garagem")
                        .HasColumnType("BIT");

                    b.Property<byte>("numero_vagas")
                        .HasColumnType("TINYINT");

                    b.Property<bool>("quintal")
                        .HasColumnType("BIT");

                    b.Property<string>("tipo")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<decimal>("valor_p_metro2")
                        .HasColumnType("SMALLMONEY");

                    b.HasKey("cod_casa");

                    b.HasIndex("Imovelcod_imovel");

                    b.HasIndex("Proprietariocod_proprietario");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("Real_Estate.Model.Endereco", b =>
                {
                    b.Property<int>("cod_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("cep")
                        .HasColumnType("CHAR(9)");

                    b.Property<string>("estado")
                        .HasColumnType("CHAR(2)");

                    b.Property<string>("logradouro")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("municipio")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("numero")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("rua")
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("cod_endereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Real_Estate.Model.Imovel", b =>
                {
                    b.Property<int>("cod_imovel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_tipoImove")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<decimal>("comprimento")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("enderecocod_endereco")
                        .HasColumnType("int");

                    b.Property<decimal>("largura")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("metro_quadrado")
                        .HasColumnType("DECIMAL(8,2)");

                    b.Property<byte>("numero_banheiros")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("numero_quartos")
                        .HasColumnType("TINYINT");

                    b.Property<int?>("proprietariocod_proprietario")
                        .HasColumnType("int");

                    b.HasKey("cod_imovel");

                    b.HasIndex("enderecocod_endereco");

                    b.HasIndex("proprietariocod_proprietario");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("Real_Estate.Model.Proprietario", b =>
                {
                    b.Property<int>("cod_proprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_proprietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cod_proprietario");

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("Real_Estate.Model.Apartamento", b =>
                {
                    b.HasOne("Real_Estate.Model.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("Imovelcod_imovel");

                    b.HasOne("Real_Estate.Model.Proprietario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("Proprietariocod_proprietario");
                });

            modelBuilder.Entity("Real_Estate.Model.Casa", b =>
                {
                    b.HasOne("Real_Estate.Model.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("Imovelcod_imovel");

                    b.HasOne("Real_Estate.Model.Proprietario", "Proprietario")
                        .WithMany()
                        .HasForeignKey("Proprietariocod_proprietario");
                });

            modelBuilder.Entity("Real_Estate.Model.Imovel", b =>
                {
                    b.HasOne("Real_Estate.Model.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecocod_endereco");

                    b.HasOne("Real_Estate.Model.Proprietario", "proprietario")
                        .WithMany("Imoveis")
                        .HasForeignKey("proprietariocod_proprietario");
                });
#pragma warning restore 612, 618
        }
    }
}
