// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real_Estate.Data;

namespace Real_Estate.Migrations
{
    [DbContext(typeof(RealEstateContext))]
    partial class RealEstateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Real_Estate.Model.Apartamento", b =>
                {
                    b.Property<int>("cod_apartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImovelRefId")
                        .HasColumnType("INT");

                    b.Property<string>("nome_bloco")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<byte>("numero_bloco")
                        .HasColumnType("TINYINT");

                    b.HasKey("cod_apartamento");

                    b.ToTable("Apartamentos");

                    b.HasData(
                        new
                        {
                            cod_apartamento = 1,
                            ImovelRefId = 3,
                            nome_bloco = "Andorinha",
                            numero_bloco = (byte)9
                        });
                });

            modelBuilder.Entity("Real_Estate.Model.Casa", b =>
                {
                    b.Property<int>("cod_casa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImovelRefId")
                        .HasColumnType("INT");

                    b.Property<bool>("garagem")
                        .HasColumnType("BIT");

                    b.Property<byte>("numero_vagas")
                        .HasColumnType("TINYINT");

                    b.Property<bool>("quintal")
                        .HasColumnType("BIT");

                    b.Property<string>("tipo")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<decimal>("valor_p_metro2")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("cod_casa");

                    b.ToTable("Casas");

                    b.HasData(
                        new
                        {
                            cod_casa = 1,
                            ImovelRefId = 1,
                            garagem = true,
                            numero_vagas = (byte)1,
                            quintal = true,
                            tipo = "HomeTown",
                            valor_p_metro2 = 25m
                        },
                        new
                        {
                            cod_casa = 2,
                            ImovelRefId = 2,
                            garagem = true,
                            numero_vagas = (byte)1,
                            quintal = false,
                            tipo = "Duplex",
                            valor_p_metro2 = 30m
                        });
                });

            modelBuilder.Entity("Real_Estate.Model.Endereco", b =>
                {
                    b.Property<int>("cod_endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bairro")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("cep")
                        .HasColumnType("CHAR(9)");

                    b.Property<string>("estado")
                        .HasColumnType("CHAR(2)");

                    b.Property<string>("logradouro")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("municipio")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("numero")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("rua")
                        .HasColumnType("VARCHAR(40)");

                    b.HasKey("cod_endereco");

                    b.ToTable("Enderecos");

                    b.HasData(
                        new
                        {
                            cod_endereco = 1,
                            bairro = "Vila Yara",
                            cep = "06026-050",
                            estado = "SP",
                            logradouro = "Rua",
                            municipio = "Osasco",
                            numero = "463",
                            rua = "Silverio Sasso"
                        },
                        new
                        {
                            cod_endereco = 2,
                            bairro = "Vila dos Remédios",
                            cep = "02675-031",
                            estado = "SP",
                            logradouro = "Avenida",
                            municipio = "São Paulo",
                            numero = "4561a",
                            rua = "dos Remedios"
                        },
                        new
                        {
                            cod_endereco = 3,
                            bairro = "Palm Desert",
                            cep = "92211",
                            estado = "CA",
                            logradouro = "Rua",
                            municipio = "California",
                            numero = "75245",
                            rua = "Vista Corona"
                        });
                });

            modelBuilder.Entity("Real_Estate.Model.Imovel", b =>
                {
                    b.Property<int>("cod_imovel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnderecoRefId")
                        .HasColumnType("int");

                    b.Property<int>("ProprietarioRefId")
                        .HasColumnType("int");

                    b.Property<int>("_tipoImovel")
                        .HasColumnType("INT");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("metro_quadrado")
                        .HasColumnType("DECIMAL(8,2)");

                    b.Property<byte>("numero_banheiros")
                        .HasColumnType("TINYINT");

                    b.Property<byte>("numero_quartos")
                        .HasColumnType("TINYINT");

                    b.HasKey("cod_imovel");

                    b.HasIndex("EnderecoRefId");

                    b.HasIndex("ProprietarioRefId");

                    b.ToTable("Imoveis");

                    b.HasData(
                        new
                        {
                            cod_imovel = 1,
                            EnderecoRefId = 1,
                            ProprietarioRefId = 1,
                            _tipoImovel = 0,
                            descricao = "Lugar agradavel com vista para calçada!",
                            metro_quadrado = 625m,
                            numero_banheiros = (byte)1,
                            numero_quartos = (byte)4
                        },
                        new
                        {
                            cod_imovel = 2,
                            EnderecoRefId = 2,
                            ProprietarioRefId = 2,
                            _tipoImovel = 0,
                            descricao = "Lindo, apenas.",
                            metro_quadrado = 2550m,
                            numero_banheiros = (byte)2,
                            numero_quartos = (byte)5
                        },
                        new
                        {
                            cod_imovel = 3,
                            EnderecoRefId = 3,
                            ProprietarioRefId = 3,
                            _tipoImovel = 1,
                            descricao = "Apartamento com uma varanda linda para o mar!",
                            metro_quadrado = 400m,
                            numero_banheiros = (byte)1,
                            numero_quartos = (byte)2
                        });
                });

            modelBuilder.Entity("Real_Estate.Model.Proprietario", b =>
                {
                    b.Property<int>("cod_proprietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_proprietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cod_proprietario");

                    b.ToTable("Proprietarios");

                    b.HasData(
                        new
                        {
                            cod_proprietario = 1,
                            email = "matmau11@hotmail.com",
                            nome_proprietario = "Matheus Costa dos Santos",
                            senha = "matmau11",
                            telefone = "954946842"
                        },
                        new
                        {
                            cod_proprietario = 2,
                            email = "maumau11@hotmail.com",
                            nome_proprietario = "Mauricio Potter dos Santos",
                            senha = "maumau11",
                            telefone = "986174471"
                        },
                        new
                        {
                            cod_proprietario = 3,
                            email = "dorivalodbrok@hotmail.com",
                            nome_proprietario = "Dorival Lodbrok",
                            senha = "doridori11",
                            telefone = "979564471"
                        });
                });

            modelBuilder.Entity("Real_Estate.Model.Imovel", b =>
                {
                    b.HasOne("Real_Estate.Model.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Real_Estate.Model.Proprietario", "Proprietario")
                        .WithMany("Imoveis")
                        .HasForeignKey("ProprietarioRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
